apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-config
  namespace: default
spec:
  encryptedData:
    values.yml: AgBPGN5mYqFCwHHbnY15pUG2SnObhrw+w2sig0Dm86bur/JmiEKhjfIRh+USkUJdilSr5gE35TlFsk7iQeZnSJhnzBIMexJz123LefTOAxsHR3w3iUV/nam59mtyPOTzM7yXksxxX0yV1vCXjt/8Hgti5wpmoIlCM6JfpQ3EhYpvUbNyy2gJ2AeLpSUDMZSuicU8fcR/Gihmhy2RVk22kTzRES2YOgTrQEPPRqP4Cx/VQaeDTRQIQf2f/F4DuQV9dlWMWIbzbSj5JDH+dJK5kgwjju/bxXCXFI532FSbOIUJAJEw3tAlbZ3DDy2lVY7ESUsG8Obc4HGeN0UhAEu79tga1tihRf9POJgIk6j0nf5xZzWes3qYK41veHW2RL1VZqXOXQ+UTSuSJNokDpDcjiSb30yR7MNGWgwYc4PPpbBkJpzCCq5LlmhOZTMuZWH5jKMSADXxxU45q7KNKlLVpDiaAupRQsWPCAGlBu8oNrM8Fs6qbIBA+6LJ+2NTzmInmjccXJU67ulEY/1IZK3ZztZiy+Vr9V5RTHkDDPWtd1wOuxSbMcrTThW6aB4GlgziNJULSHCPBJtpu7AqUtoiDuFKE7qNZz81/1WGi4USoBAwRmk3A2M8Sb6eLIYgNq1ofOPdwta4QXWvND+ld33llHh6GqdnC/g1g+HlLfHlbYoHN49+cQ4oVhGfq0RLjHIl1I7ocOSnUN7cjB9yreplxPh1lUy9zrMZPzBU24bsn14APXSmrn9xg9RBkHLBkDWaz3b3002yDDYRCv4KbAzSh2XLNy7Avw40fO+IQ1pwNC3rKoG5V6qay/cDx9ju+wenDshR8jABA43679mFcpEK3AYfnRSg8xsD1ze04UlefXqLIVsD5R71i3rqoSiJvJpPQAUWKfa2kRl/CshOkIKgQ+9wGZZXn6tAGZibutVVVm+nYKBxXautn53cth6+CvskOVAtxIliM3nThRbnU2fTKbMWhxLaU0nAkuHPVW8sZB6H9tLX8V+jQ9DhvJ9T5XMe+kUW+PgGZ4LbGnCz1YLWcsU2dzqr0J4N75pOMi8OACQ21xNKmU34iLcsL3JVWd2Gm8k7uWoLDFVpXVzQCZU=
  template:
    metadata:
      creationTimestamp: null
      name: influxdb-config
      namespace: default
status: {}

